# Generated by Django 4.2.6 on 2023-10-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='display_name',
            field=models.CharField(default='Man & Woman Fashion', max_length=255),
            preserve_default=False,
        ),
    ]
